version: '3.9'

services:
  configserver:
    image: "ghcr.io/mazaadak/config-server:latest"
    container_name: configserver
    ports:
      - "18071:18071"
    healthcheck:
      test: "curl --fail --silent localhost:18071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      MAZADAK_GITHUB_TOKEN: ${MAZADAK_GITHUB_TOKEN}
    extends:
      file: common-config.yml
      service: service-base-config

  eurekaserver:
    image: "ghcr.io/mazaadak/eureka-server:latest"
    container_name: eurekaserver
    ports:
      - "18050:18050"
    depends_on:
      configserver:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:18050/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: config-server-config

  mazadakgateway:
    image: "ghcr.io/mazaadak/mazadak-gateway:latest"
    container_name: mazadak-gateway
    ports:
      - "18090:18090"
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: eureka-config

  broker:
    image: apache/kafka-native:4.0.1-rc2
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://broker:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    extends:
      file: common-config.yml
      service: network

  product_catalog:
    image: product_catalog:latest
    container_name: product_catalog
    ports:
      - "18089:18089"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: broker:9092
      SPRING_CONFIG_IMPORT: optional:configserver:http://configserver:18071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:18050/eureka/
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
      broker:
        condition: service_started
    networks:
      - mazadak

networks:
  mazadak:
    driver: bridge
