spring:
  application:
    name: product-catalog
  config:
    import: "optional:configserver:http://localhost:18071/"

  datasource:
    url: jdbc:h2:mem:product_catalog;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  flyway:
    enabled: false

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        inventoryDeleted-in-0:
          destination: inventory-deleted
          group: product-catalog
        auctionDeleted-in-0:
          destination: auction-deleted
          group: product-catalog
        auctionStarted-in-0:
          destination: auction-started
          group: product-catalog
        auctionEnded-in-0:
          destination: auction-ended
          group: product-catalog
    function:
      definition: auctionDeleted;auctionStarted;auctionEnded;inventoryDeleted


temporal:
  address: ${TEMPORAL_ADDRESS:127.0.0.1:7233}